services:

  postgres:
    image: postgres:16-alpine
    container_name: bebasqc_postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - bebasqc_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    image: ghcr.io/geraldman/bebas-qc/backend:latest
    container_name: bebasqc_backend
    env_file: .env
    environment:
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      ROBOFLOW_IMAGE_DIR: /app/assets/roboflow
    volumes:
      - ./assets/roboflow:/app/assets/roboflow:ro
    ports:
      - "8085:8080"
    depends_on:
      postgres:
        condition: service_healthy
      hivemq:
        condition: service_started
    networks:
      - bebasqc_network
    restart: unless-stopped
  
  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    image: ghcr.io/geraldman/bebas-qc/frontend:latest
    container_name: bebasqc_frontend
    ports:
      - "3003:88"
    depends_on:
      - backend
    networks:
      - bebasqc_network
    restart: unless-stopped
  
  nginx:
    image: nginx:alpine
    container_name: bebasqc_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/generate-dummy-certs.sh:/docker-entrypoint.d/00-generate-dummy-certs.sh:ro
      - ./docker/certbot/www:/var/www/certbot:ro
      - ./docker/certbot/conf:/etc/letsencrypt:rw
    depends_on:
      - frontend
      - backend
      - hivemq
    networks:
      - bebasqc_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: bebasqc_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bebasqc_network
    restart: unless-stopped
  
  hivemq:
    image: hivemq/hivemq-ce:latest
    container_name: bebasqc_hivemq
    ports:
      - "1883:1883"     # MQTT
      - "8000:8000"     # WebSocket
    volumes:
      - ./docker/hivemq/config/config.xml:/opt/hivemq/conf/config.xml
      - hivemq_data:/opt/hivemq/data
      - hivemq_log:/opt/hivemq/log
    environment:
      - HIVEMQ_ALLOW_ALL_CONNECTIONS=true   # pls change/config it before prod
    networks:
      - bebasqc_network
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: bebasqc_n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_PATH=/
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678
      - GENERIC_TIMEZONE=Asia/Jakarta
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - CREDENTIALS_OVERWRITE_DATA={"postgres":{"host":"postgres","port":5432,"database":"${POSTGRES_DB}","user":"${POSTGRES_USER}","password":"${POSTGRES_PASSWORD}"},"telegramApi":{"accessToken":"${TELEGRAM_BOT_TOKEN}"}}
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres
    networks:
      - bebasqc_network
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    container_name: bebasqc_certbot
    volumes:
      - ./docker/certbot/www:/var/www/certbot:rw
      - ./docker/certbot/conf:/etc/letsencrypt:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - bebasqc_network

volumes:
  postgres_data:
  redis_data:
  n8n_data:
  hivemq_data:
  hivemq_log:

networks:
  bebasqc_network:
    driver: bridge