services:

  postgres:
    image: postgres:16-alpine
    container_name: bebasqc_postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - bebasqc_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    container_name: bebasqc_backend
    env_file: .env
    environment:
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      hivemq:
        condition: service_started
    networks:
      - bebasqc_network
    restart: unless-stopped
  
  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    container_name: bebasqc_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - bebasqc_network
    restart: unless-stopped
  
  nginx:
    image: nginx:alpine
    container_name: bebasqc_nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - bebasqc_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: bebasqc_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bebasqc_network
  
  hivemq:
    image: hivemq/hivemq-ce:latest
    container_name: bebasqc_hivemq
    ports:
      - "1883:1883"     # MQTT
      - "8000:8000"     # WebSocket
    volumes:
      - ./docker/hivemq/config/config.xml:/opt/hivemq/conf/config.xml
      - ./docker/hivemq/data:/opt/hivemq/data
      - ./docker/hivemq/log:/opt/hivemq/log
    environment:
      - HIVEMQ_ALLOW_ALL_CONNECTIONS=true   # pls change/config it before prod
    networks:
      - bebasqc_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090"]
      interval: 30s
      timeout: 10s
      retries: 5

  n8n:
    image: n8nio/n8n:latest
    container_name: bebasqc_n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Asia/Jakarta
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=bebasqc123
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres
    networks:
      - bebasqc_network
    restart: unless-stopped

  mqtt-simulator: # this is used to simulate the inputs for the model
    build:
      context: ./services/mqtt-simulator
      dockerfile: Dockerfile
    container_name: bebasqc_mqtt_simulator
    ports:
      - "4000:80"
    depends_on:
      - hivemq
    networks:
      - bebasqc_network

volumes:
  postgres_data:
  redis_data:
  n8n_data:

networks:
  bebasqc_network:
    driver: bridge