upstream frontend{
    server frontend:80;
}

upstream backend{
    server backend:8080;
}

# 1. Redirect IP address (or any other domain) to the proper domain
server {
    listen 80 default_server;
    server_name _;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 http://bebasqc.geraldmanurung.site$request_uri;
    }
}

# 2. Redirect bebasqc.geraldmanurung.site HTTP traffic to HTTPS (except Let's Encrypt challenge)
server {
    listen 80;
    server_name bebasqc.geraldmanurung.site;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# 3. SSL Server Block
server {
    listen 443 ssl;
    server_name bebasqc.geraldmanurung.site;

    ssl_certificate /etc/letsencrypt/live/bebasqc.geraldmanurung.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bebasqc.geraldmanurung.site/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://frontend;
    }

    location /api/ {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /assets/roboflow/ {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /n8n/ {
        proxy_pass http://n8n:5678;
        proxy_set_header Connection '';
        proxy_http_version 1.1;
        chunked_transfer_encoding off;
        proxy_buffering off;
        proxy_cache off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}